name: Compile Assets

on:
  push:
    branches:
      - '2.*'
    paths:
      - 'resources/assets/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  compile-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Compile Assets
        run: npm run build

      - name: Deploy compiled assets
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: Build assets
          push_options: '--force'